name: Build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: run build.sh
        run: ./build.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.tar.gz"